layout_spectrum: 0.09036316
typography_spectrum: 0.9423819
color:
  saturation: 0.8053019
  lightness: 0.02001297
  brandStrength: 0.3734413
  rhythmicContrast: 0.4250034
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Elena
